# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainAnalyzer.ui'
#
# Created: Wed Feb  2 17:03:18 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(957, 838)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setSizeIncrement(QtCore.QSize(1, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 12, 1, 1, 2)
        self.line = QtGui.QFrame(self.centralWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 11, 1, 1, 6)
        self.buttonAddFiles = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonAddFiles.sizePolicy().hasHeightForWidth())
        self.buttonAddFiles.setSizePolicy(sizePolicy)
        self.buttonAddFiles.setObjectName("buttonAddFiles")
        self.gridLayout.addWidget(self.buttonAddFiles, 14, 1, 1, 1)
        self.buttonRemoveFiles = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonRemoveFiles.sizePolicy().hasHeightForWidth())
        self.buttonRemoveFiles.setSizePolicy(sizePolicy)
        self.buttonRemoveFiles.setObjectName("buttonRemoveFiles")
        self.gridLayout.addWidget(self.buttonRemoveFiles, 14, 2, 1, 1)
        self.listFiles = QtGui.QListView(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listFiles.sizePolicy().hasHeightForWidth())
        self.listFiles.setSizePolicy(sizePolicy)
        self.listFiles.setSizeIncrement(QtCore.QSize(1, 0))
        self.listFiles.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listFiles.setObjectName("listFiles")
        self.gridLayout.addWidget(self.listFiles, 13, 1, 1, 2)
        self.lineeditQuickSearch = QtGui.QLineEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineeditQuickSearch.sizePolicy().hasHeightForWidth())
        self.lineeditQuickSearch.setSizePolicy(sizePolicy)
        self.lineeditQuickSearch.setObjectName("lineeditQuickSearch")
        self.gridLayout.addWidget(self.lineeditQuickSearch, 14, 4, 1, 3)
        self.buttonClearAllSearches = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonClearAllSearches.sizePolicy().hasHeightForWidth())
        self.buttonClearAllSearches.setSizePolicy(sizePolicy)
        self.buttonClearAllSearches.setObjectName("buttonClearAllSearches")
        self.gridLayout.addWidget(self.buttonClearAllSearches, 3, 2, 1, 1)
        self.buttonSearch = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonSearch.sizePolicy().hasHeightForWidth())
        self.buttonSearch.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.buttonSearch.setFont(font)
        self.buttonSearch.setObjectName("buttonSearch")
        self.gridLayout.addWidget(self.buttonSearch, 3, 4, 1, 3)
        self.buttonSaveSearches = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonSaveSearches.sizePolicy().hasHeightForWidth())
        self.buttonSaveSearches.setSizePolicy(sizePolicy)
        self.buttonSaveSearches.setObjectName("buttonSaveSearches")
        self.gridLayout.addWidget(self.buttonSaveSearches, 3, 3, 1, 1)
        self.texteditInterlinear = PoioIlTextEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.texteditInterlinear.sizePolicy().hasHeightForWidth())
        self.texteditInterlinear.setSizePolicy(sizePolicy)
        self.texteditInterlinear.setSizeIncrement(QtCore.QSize(2, 0))
        self.texteditInterlinear.setFrameShadow(QtGui.QFrame.Sunken)
        self.texteditInterlinear.setObjectName("texteditInterlinear")
        self.gridLayout.addWidget(self.texteditInterlinear, 13, 3, 1, 4)
        self.label_8 = QtGui.QLabel(self.centralWidget)
        self.label_8.setSizeIncrement(QtCore.QSize(2, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 12, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 14, 3, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setSizeIncrement(QtCore.QSize(1, 0))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineeditSearchUtterances = QtGui.QLineEdit(self.tab)
        self.lineeditSearchUtterances.setSizeIncrement(QtCore.QSize(2, 0))
        self.lineeditSearchUtterances.setObjectName("lineeditSearchUtterances")
        self.gridLayout_2.addWidget(self.lineeditSearchUtterances, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setSizeIncrement(QtCore.QSize(1, 0))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineeditSearchWords = QtGui.QLineEdit(self.tab)
        self.lineeditSearchWords.setSizeIncrement(QtCore.QSize(2, 0))
        self.lineeditSearchWords.setObjectName("lineeditSearchWords")
        self.gridLayout_2.addWidget(self.lineeditSearchWords, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setSizeIncrement(QtCore.QSize(1, 0))
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.lineeditSearchMorphemes = QtGui.QLineEdit(self.tab)
        self.lineeditSearchMorphemes.setSizeIncrement(QtCore.QSize(2, 0))
        self.lineeditSearchMorphemes.setObjectName("lineeditSearchMorphemes")
        self.gridLayout_2.addWidget(self.lineeditSearchMorphemes, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setSizeIncrement(QtCore.QSize(1, 0))
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.lineeditSearchGlosses = QtGui.QLineEdit(self.tab)
        self.lineeditSearchGlosses.setSizeIncrement(QtCore.QSize(2, 0))
        self.lineeditSearchGlosses.setObjectName("lineeditSearchGlosses")
        self.gridLayout_2.addWidget(self.lineeditSearchGlosses, 3, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setSizeIncrement(QtCore.QSize(1, 0))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.lineeditSearchTranslations = QtGui.QLineEdit(self.tab)
        self.lineeditSearchTranslations.setSizeIncrement(QtCore.QSize(2, 0))
        self.lineeditSearchTranslations.setObjectName("lineeditSearchTranslations")
        self.gridLayout_2.addWidget(self.lineeditSearchTranslations, 4, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radiobuttonAnd = QtGui.QRadioButton(self.groupBox)
        self.radiobuttonAnd.setChecked(True)
        self.radiobuttonAnd.setObjectName("radiobuttonAnd")
        self.verticalLayout_4.addWidget(self.radiobuttonAnd)
        self.radiobuttonOr = QtGui.QRadioButton(self.groupBox)
        self.radiobuttonOr.setObjectName("radiobuttonOr")
        self.verticalLayout_4.addWidget(self.radiobuttonOr)
        self.checkboxInvert = QtGui.QCheckBox(self.groupBox)
        self.checkboxInvert.setObjectName("checkboxInvert")
        self.verticalLayout_4.addWidget(self.checkboxInvert)
        self.checkboxContained = QtGui.QCheckBox(self.groupBox)
        self.checkboxContained.setObjectName("checkboxContained")
        self.verticalLayout_4.addWidget(self.checkboxContained)
        self.gridLayout_2.addWidget(self.groupBox, 0, 3, 5, 1)
        self.line_2 = QtGui.QFrame(self.tab)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 0, 2, 5, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 2, 1, 1, 6)
        self.buttonAlignCenter = QtGui.QToolButton(self.centralWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/pixmaps/aligncenter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonAlignCenter.setIcon(icon)
        self.buttonAlignCenter.setIconSize(QtCore.QSize(24, 24))
        self.buttonAlignCenter.setCheckable(True)
        self.buttonAlignCenter.setAutoRaise(True)
        self.buttonAlignCenter.setObjectName("buttonAlignCenter")
        self.gridLayout.addWidget(self.buttonAlignCenter, 12, 6, 1, 1)
        self.buttonAlignLeft = QtGui.QToolButton(self.centralWidget)
        self.buttonAlignLeft.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/pixmaps/alignleft.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonAlignLeft.setIcon(icon1)
        self.buttonAlignLeft.setIconSize(QtCore.QSize(24, 24))
        self.buttonAlignLeft.setCheckable(True)
        self.buttonAlignLeft.setChecked(True)
        self.buttonAlignLeft.setAutoRaise(True)
        self.buttonAlignLeft.setObjectName("buttonAlignLeft")
        self.gridLayout.addWidget(self.buttonAlignLeft, 12, 5, 1, 1)
        self.buttonClearThisSearch = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonClearThisSearch.sizePolicy().hasHeightForWidth())
        self.buttonClearThisSearch.setSizePolicy(sizePolicy)
        self.buttonClearThisSearch.setObjectName("buttonClearThisSearch")
        self.gridLayout.addWidget(self.buttonClearThisSearch, 3, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 957, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuFiel = QtGui.QMenu(self.menuBar)
        self.menuFiel.setObjectName("menuFiel")
        self.menuEdit = QtGui.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuAbout = QtGui.QMenu(self.menuBar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menuBar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAddFiles = QtGui.QAction(MainWindow)
        self.actionAddFiles.setObjectName("actionAddFiles")
        self.actionRemoveFiles = QtGui.QAction(MainWindow)
        self.actionRemoveFiles.setObjectName("actionRemoveFiles")
        self.actionNewProject = QtGui.QAction(MainWindow)
        self.actionNewProject.setObjectName("actionNewProject")
        self.actionSaveProject = QtGui.QAction(MainWindow)
        self.actionSaveProject.setObjectName("actionSaveProject")
        self.actionSaveProjectAs = QtGui.QAction(MainWindow)
        self.actionSaveProjectAs.setObjectName("actionSaveProjectAs")
        self.actionEditWordClasses = QtGui.QAction(MainWindow)
        self.actionEditWordClasses.setObjectName("actionEditWordClasses")
        self.actionSearches = QtGui.QAction(MainWindow)
        self.actionSearches.setObjectName("actionSearches")
        self.actionAboutPoioAnalyzer = QtGui.QAction(MainWindow)
        self.actionAboutPoioAnalyzer.setObjectName("actionAboutPoioAnalyzer")
        self.actionQuickSearch = QtGui.QAction(MainWindow)
        self.actionQuickSearch.setObjectName("actionQuickSearch")
        self.menuFiel.addAction(self.actionNewProject)
        self.menuFiel.addAction(self.actionSaveProject)
        self.menuFiel.addAction(self.actionSaveProjectAs)
        self.menuFiel.addSeparator()
        self.menuFiel.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionAddFiles)
        self.menuEdit.addAction(self.actionRemoveFiles)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionEditWordClasses)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSearches)
        self.menuEdit.addAction(self.actionQuickSearch)
        self.menuAbout.addAction(self.actionAboutPoioAnalyzer)
        self.menuBar.addAction(self.menuFiel.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.lineeditSearchUtterances)
        MainWindow.setTabOrder(self.lineeditSearchUtterances, self.lineeditSearchWords)
        MainWindow.setTabOrder(self.lineeditSearchWords, self.lineeditSearchMorphemes)
        MainWindow.setTabOrder(self.lineeditSearchMorphemes, self.lineeditSearchGlosses)
        MainWindow.setTabOrder(self.lineeditSearchGlosses, self.lineeditSearchTranslations)
        MainWindow.setTabOrder(self.lineeditSearchTranslations, self.radiobuttonAnd)
        MainWindow.setTabOrder(self.radiobuttonAnd, self.radiobuttonOr)
        MainWindow.setTabOrder(self.radiobuttonOr, self.checkboxInvert)
        MainWindow.setTabOrder(self.checkboxInvert, self.checkboxContained)
        MainWindow.setTabOrder(self.checkboxContained, self.buttonClearThisSearch)
        MainWindow.setTabOrder(self.buttonClearThisSearch, self.buttonClearAllSearches)
        MainWindow.setTabOrder(self.buttonClearAllSearches, self.buttonSaveSearches)
        MainWindow.setTabOrder(self.buttonSaveSearches, self.buttonSearch)
        MainWindow.setTabOrder(self.buttonSearch, self.listFiles)
        MainWindow.setTabOrder(self.listFiles, self.texteditInterlinear)
        MainWindow.setTabOrder(self.texteditInterlinear, self.buttonAlignLeft)
        MainWindow.setTabOrder(self.buttonAlignLeft, self.buttonAlignCenter)
        MainWindow.setTabOrder(self.buttonAlignCenter, self.buttonAddFiles)
        MainWindow.setTabOrder(self.buttonAddFiles, self.buttonRemoveFiles)
        MainWindow.setTabOrder(self.buttonRemoveFiles, self.lineeditQuickSearch)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "PoioAnalyzer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Files:", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonAddFiles.setText(QtGui.QApplication.translate("MainWindow", "Add files...", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonRemoveFiles.setText(QtGui.QApplication.translate("MainWindow", "Remove files", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonClearAllSearches.setText(QtGui.QApplication.translate("MainWindow", "Clear All Searches", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSearch.setText(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSaveSearches.setText(QtGui.QApplication.translate("MainWindow", "Save Searches...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Result:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Quick Search:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Utterances:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Words:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Morphemes:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Glosses:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Translations:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Search Options", None, QtGui.QApplication.UnicodeUTF8))
        self.radiobuttonAnd.setText(QtGui.QApplication.translate("MainWindow", "AND", None, QtGui.QApplication.UnicodeUTF8))
        self.radiobuttonOr.setText(QtGui.QApplication.translate("MainWindow", "OR", None, QtGui.QApplication.UnicodeUTF8))
        self.checkboxInvert.setText(QtGui.QApplication.translate("MainWindow", "NOT", None, QtGui.QApplication.UnicodeUTF8))
        self.checkboxContained.setText(QtGui.QApplication.translate("MainWindow", "contained matches", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Search 1", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "New Search...", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonAlignCenter.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonAlignLeft.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonClearThisSearch.setText(QtGui.QApplication.translate("MainWindow", "Clear This Search", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFiel.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddFiles.setText(QtGui.QApplication.translate("MainWindow", "Add Files...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemoveFiles.setText(QtGui.QApplication.translate("MainWindow", "Remove Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewProject.setText(QtGui.QApplication.translate("MainWindow", "New Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveProject.setText(QtGui.QApplication.translate("MainWindow", "Save Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveProjectAs.setText(QtGui.QApplication.translate("MainWindow", "Save Project As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditWordClasses.setText(QtGui.QApplication.translate("MainWindow", "Edit Word Classes...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSearches.setText(QtGui.QApplication.translate("MainWindow", "Searches...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAboutPoioAnalyzer.setText(QtGui.QApplication.translate("MainWindow", "About PoioAnalyzer...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuickSearch.setText(QtGui.QApplication.translate("MainWindow", "Quick Search", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuickSearch.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))

from PoioIlTextEdit import PoioIlTextEdit
import poioanalyzer_rc
