# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowGRAID.ui'
#
# Created: Tue May 28 11:30:41 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1014, 836)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(5, -1, -1, -1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayoutMain = QtGui.QVBoxLayout()
        self.verticalLayoutMain.setObjectName(_fromUtf8("verticalLayoutMain"))
        self.horizontalLayoutEditArea = QtGui.QHBoxLayout()
        self.horizontalLayoutEditArea.setObjectName(_fromUtf8("horizontalLayoutEditArea"))
        self.textedit = PoioGraidTextEdit(self.centralWidget)
        self.textedit.setObjectName(_fromUtf8("textedit"))
        self.horizontalLayoutEditArea.addWidget(self.textedit)
        self.verticalLayoutMain.addLayout(self.horizontalLayoutEditArea)
        self.gridLayout.addLayout(self.verticalLayoutMain, 1, 2, 1, 1)
        self.openProject = QtGui.QWidget(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openProject.sizePolicy().hasHeightForWidth())
        self.openProject.setSizePolicy(sizePolicy)
        self.openProject.setMaximumSize(QtCore.QSize(20, 16777215))
        self.openProject.setObjectName(_fromUtf8("openProject"))
        self.verticalLayout = QtGui.QVBoxLayout(self.openProject)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.projectBtn = QtGui.QPushButton(self.openProject)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projectBtn.sizePolicy().hasHeightForWidth())
        self.projectBtn.setSizePolicy(sizePolicy)
        self.projectBtn.setMaximumSize(QtCore.QSize(20, 16777215))
        self.projectBtn.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.projectBtn.setCheckable(True)
        self.projectBtn.setAutoDefault(False)
        self.projectBtn.setDefault(False)
        self.projectBtn.setFlat(False)
        self.projectBtn.setObjectName(_fromUtf8("projectBtn"))
        self.verticalLayout.addWidget(self.projectBtn)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.openProject, 1, 0, 1, 1)
        self.projectManager = QtGui.QWidget(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projectManager.sizePolicy().hasHeightForWidth())
        self.projectManager.setSizePolicy(sizePolicy)
        self.projectManager.setMinimumSize(QtCore.QSize(130, 150))
        self.projectManager.setMaximumSize(QtCore.QSize(250, 16777215))
        self.projectManager.setObjectName(_fromUtf8("projectManager"))
        self.gridLayout_2 = QtGui.QGridLayout(self.projectManager)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setHorizontalSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.removefileBtn = QtGui.QPushButton(self.projectManager)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/pixmaps/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.removefileBtn.setIcon(icon)
        self.removefileBtn.setObjectName(_fromUtf8("removefileBtn"))
        self.gridLayout_2.addWidget(self.removefileBtn, 2, 1, 1, 1)
        self.addfileBtn = QtGui.QPushButton(self.projectManager)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/pixmaps/projectopen.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addfileBtn.setIcon(icon1)
        self.addfileBtn.setObjectName(_fromUtf8("addfileBtn"))
        self.gridLayout_2.addWidget(self.addfileBtn, 2, 0, 1, 1)
        self.label = QtGui.QLabel(self.projectManager)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.listFiles = QtGui.QListView(self.projectManager)
        self.listFiles.setObjectName(_fromUtf8("listFiles"))
        self.gridLayout_2.addWidget(self.listFiles, 1, 0, 1, 2)
        self.saveprojectBtn = QtGui.QPushButton(self.projectManager)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/pixmaps/filesave.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.saveprojectBtn.setIcon(icon2)
        self.saveprojectBtn.setObjectName(_fromUtf8("saveprojectBtn"))
        self.gridLayout_2.addWidget(self.saveprojectBtn, 4, 0, 1, 2)
        self.openprojectBtn = QtGui.QPushButton(self.projectManager)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/pixmaps/fileopen.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.openprojectBtn.setIcon(icon3)
        self.openprojectBtn.setObjectName(_fromUtf8("openprojectBtn"))
        self.gridLayout_2.addWidget(self.openprojectBtn, 3, 0, 1, 2)
        self.gridLayout.addWidget(self.projectManager, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1014, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menuBar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuAbout = QtGui.QMenu(self.menuBar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpenFile = QtGui.QAction(MainWindow)
        self.actionOpenFile.setIcon(icon1)
        self.actionOpenFile.setObjectName(_fromUtf8("actionOpenFile"))
        self.actionSaveFile = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/pixmaps/filesave.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveFile.setIcon(icon4)
        self.actionSaveFile.setObjectName(_fromUtf8("actionSaveFile"))
        self.actionSaveFileAs = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/pixmaps/filesaveas.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveFileAs.setIcon(icon5)
        self.actionSaveFileAs.setObjectName(_fromUtf8("actionSaveFileAs"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionNewFile = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/pixmaps/filenew.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNewFile.setIcon(icon6)
        self.actionNewFile.setObjectName(_fromUtf8("actionNewFile"))
        self.actionDeleteUtterance = QtGui.QAction(MainWindow)
        self.actionDeleteUtterance.setEnabled(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/pixmaps/removeutterance.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeleteUtterance.setIcon(icon7)
        self.actionDeleteUtterance.setObjectName(_fromUtf8("actionDeleteUtterance"))
        self.actionCopyUtterance = QtGui.QAction(MainWindow)
        self.actionCopyUtterance.setEnabled(False)
        self.actionCopyUtterance.setObjectName(_fromUtf8("actionCopyUtterance"))
        self.actionDeleteColumn = QtGui.QAction(MainWindow)
        self.actionDeleteColumn.setEnabled(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/pixmaps/removeword.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeleteColumn.setIcon(icon8)
        self.actionDeleteColumn.setObjectName(_fromUtf8("actionDeleteColumn"))
        self.actionAboutPoioGRAID = QtGui.QAction(MainWindow)
        self.actionAboutPoioGRAID.setObjectName(_fromUtf8("actionAboutPoioGRAID"))
        self.actionOptions = QtGui.QAction(MainWindow)
        self.actionOptions.setEnabled(False)
        self.actionOptions.setObjectName(_fromUtf8("actionOptions"))
        self.actionInsertColumnBefore = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/pixmaps/insertcolumnbefore.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInsertColumnBefore.setIcon(icon9)
        self.actionInsertColumnBefore.setObjectName(_fromUtf8("actionInsertColumnBefore"))
        self.actionInsertColumnAfter = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/pixmaps/insertcolumnafter.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInsertColumnAfter.setIcon(icon10)
        self.actionInsertColumnAfter.setObjectName(_fromUtf8("actionInsertColumnAfter"))
        self.actionInsertUtteranceBefore = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/pixmaps/insertutterancebefore.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInsertUtteranceBefore.setIcon(icon11)
        self.actionInsertUtteranceBefore.setObjectName(_fromUtf8("actionInsertUtteranceBefore"))
        self.actionInsertUtteranceAfter = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/pixmaps/insertutteranceafter.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInsertUtteranceAfter.setIcon(icon12)
        self.actionInsertUtteranceAfter.setObjectName(_fromUtf8("actionInsertUtteranceAfter"))
        self.actionFind = QtGui.QAction(MainWindow)
        self.actionFind.setObjectName(_fromUtf8("actionFind"))
        self.actionFindAndReplace = QtGui.QAction(MainWindow)
        self.actionFindAndReplace.setObjectName(_fromUtf8("actionFindAndReplace"))
        self.actionSave_Project = QtGui.QAction(MainWindow)
        self.actionSave_Project.setIcon(icon4)
        self.actionSave_Project.setObjectName(_fromUtf8("actionSave_Project"))
        self.actionSave_Project_as = QtGui.QAction(MainWindow)
        self.actionSave_Project_as.setIcon(icon5)
        self.actionSave_Project_as.setObjectName(_fromUtf8("actionSave_Project_as"))
        self.actionOpen_Project = QtGui.QAction(MainWindow)
        self.actionOpen_Project.setIcon(icon3)
        self.actionOpen_Project.setObjectName(_fromUtf8("actionOpen_Project"))
        self.menuFile.addAction(self.actionNewFile)
        self.menuFile.addAction(self.actionOpenFile)
        self.menuFile.addAction(self.actionSaveFile)
        self.menuFile.addAction(self.actionSaveFileAs)
        self.menuFile.addAction(self.actionOpen_Project)
        self.menuFile.addAction(self.actionSave_Project)
        self.menuFile.addAction(self.actionSave_Project_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionCopyUtterance)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionInsertUtteranceAfter)
        self.menuEdit.addAction(self.actionInsertUtteranceBefore)
        self.menuEdit.addAction(self.actionDeleteUtterance)
        self.menuEdit.addAction(self.actionInsertColumnBefore)
        self.menuEdit.addAction(self.actionInsertColumnAfter)
        self.menuEdit.addAction(self.actionDeleteColumn)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionFind)
        self.menuEdit.addAction(self.actionFindAndReplace)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionOptions)
        self.menuAbout.addAction(self.actionAboutPoioGRAID)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())
        self.toolBar.addAction(self.actionNewFile)
        self.toolBar.addAction(self.actionOpenFile)
        self.toolBar.addAction(self.actionSaveFile)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionInsertUtteranceBefore)
        self.toolBar.addAction(self.actionInsertUtteranceAfter)
        self.toolBar.addAction(self.actionDeleteUtterance)
        self.toolBar.addAction(self.actionInsertColumnBefore)
        self.toolBar.addAction(self.actionInsertColumnAfter)
        self.toolBar.addAction(self.actionDeleteColumn)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.projectBtn, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.projectManager.setShown)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "PoioGRAID", None))
        self.projectBtn.setToolTip(_translate("MainWindow", "Show/hide Project Manager", None))
        self.projectBtn.setText(_translate("MainWindow", "P\n"
"r\n"
"o\n"
"j\n"
"e\n"
"c\n"
"t", None))
        self.removefileBtn.setText(_translate("MainWindow", "Remove File", None))
        self.addfileBtn.setText(_translate("MainWindow", "Add File", None))
        self.label.setText(_translate("MainWindow", "    Files:", None))
        self.saveprojectBtn.setText(_translate("MainWindow", "Save Project", None))
        self.openprojectBtn.setText(_translate("MainWindow", "Open Project", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionOpenFile.setText(_translate("MainWindow", "Open File...", None))
        self.actionOpenFile.setToolTip(_translate("MainWindow", "Open File", None))
        self.actionOpenFile.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionSaveFile.setText(_translate("MainWindow", "Save File", None))
        self.actionSaveFile.setToolTip(_translate("MainWindow", "Save File", None))
        self.actionSaveFile.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionSaveFileAs.setText(_translate("MainWindow", "Save File as...", None))
        self.actionSaveFileAs.setToolTip(_translate("MainWindow", "Save File As", None))
        self.actionSaveFileAs.setShortcut(_translate("MainWindow", "Ctrl+Alt+S", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionNewFile.setText(_translate("MainWindow", "New File...", None))
        self.actionNewFile.setToolTip(_translate("MainWindow", "Create a new annotation file", None))
        self.actionNewFile.setShortcut(_translate("MainWindow", "Ctrl+N", None))
        self.actionDeleteUtterance.setText(_translate("MainWindow", "Delete utterance", None))
        self.actionCopyUtterance.setText(_translate("MainWindow", "Copy utterance", None))
        self.actionCopyUtterance.setShortcut(_translate("MainWindow", "Ctrl+C", None))
        self.actionDeleteColumn.setText(_translate("MainWindow", "Delete column", None))
        self.actionDeleteColumn.setToolTip(_translate("MainWindow", "Delete column", None))
        self.actionDeleteColumn.setShortcut(_translate("MainWindow", "Ctrl+D", None))
        self.actionAboutPoioGRAID.setText(_translate("MainWindow", "About PoioGRAID...", None))
        self.actionAboutPoioGRAID.setToolTip(_translate("MainWindow", "About PoioGRAID", None))
        self.actionOptions.setText(_translate("MainWindow", "Options...", None))
        self.actionInsertColumnBefore.setText(_translate("MainWindow", "Insert empty column before", None))
        self.actionInsertColumnAfter.setText(_translate("MainWindow", "Insert empty column after", None))
        self.actionInsertUtteranceBefore.setText(_translate("MainWindow", "Insert empty utterance before", None))
        self.actionInsertUtteranceBefore.setToolTip(_translate("MainWindow", "Insert utterance before", None))
        self.actionInsertUtteranceAfter.setText(_translate("MainWindow", "Insert empty utterance after", None))
        self.actionFind.setText(_translate("MainWindow", "Find...", None))
        self.actionFind.setShortcut(_translate("MainWindow", "Ctrl+F", None))
        self.actionFindAndReplace.setText(_translate("MainWindow", "Find and Replace...", None))
        self.actionFindAndReplace.setShortcut(_translate("MainWindow", "Ctrl+R", None))
        self.actionSave_Project.setText(_translate("MainWindow", "Save Project", None))
        self.actionSave_Project_as.setText(_translate("MainWindow", "Save Project as...", None))
        self.actionOpen_Project.setText(_translate("MainWindow", "Open Project", None))

from poio.ui.PoioGraidTextEdit import PoioGraidTextEdit
import poio.ui.poio_rc
